winedata <- read.csv("/Users/jacobwatson/Downloads/WineQT.csv", 
                     na.strings = c("NA", "NaN", "", "?")) 

summary(winedata$fixed.acidity)
summary(winedata$volatile.acidity)
summary(winedata$citric.acid)
summary(winedata$residual.sugar)
summary(winedata$chlorides)
summary(winedata$free.sulfur.dioxide)
summary(winedata$total.sulfur.dioxide)
summary(winedata$density)
summary(winedata$pH)
summary(winedata$sulphates)
summary(winedata$alcohol)
summary(winedata$quality)
summary(winedata$Id)

sd(winedata$fixed.acidity)
sd(winedata$volatile.acidity)
sd(winedata$citric.acid)
sd(winedata$residual.sugar)
sd(winedata$chlorides)
sd(winedata$free.sulfur.dioxide)
sd(winedata$total.sulfur.dioxide)
sd(winedata$density)
sd(winedata$pH)
sd(winedata$sulphates)
sd(winedata$alcohol)
sd(winedata$quality)
sd(winedata$Id)